// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagsToMedia(arg1, arg2) {
  return window['go']['app']['App']['AddTagsToMedia'](arg1, arg2);
}

export function CheckDatabaseIntegrity() {
  return window['go']['app']['App']['CheckDatabaseIntegrity']();
}

export function CreateTag(arg1) {
  return window['go']['app']['App']['CreateTag'](arg1);
}

export function DeleteMedia(arg1) {
  return window['go']['app']['App']['DeleteMedia'](arg1);
}

export function GetAllMedia(arg1, arg2) {
  return window['go']['app']['App']['GetAllMedia'](arg1, arg2);
}

export function GetAllTags(arg1, arg2) {
  return window['go']['app']['App']['GetAllTags'](arg1, arg2);
}

export function GetDatabaseStats() {
  return window['go']['app']['App']['GetDatabaseStats']();
}

export function GetMediaByID(arg1) {
  return window['go']['app']['App']['GetMediaByID'](arg1);
}

export function GetMediaByTag(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMediaByTag'](arg1, arg2, arg3);
}

export function GetMediaPath(arg1) {
  return window['go']['app']['App']['GetMediaPath'](arg1);
}

export function GetTagsForMedia(arg1) {
  return window['go']['app']['App']['GetTagsForMedia'](arg1);
}

export function GetThumbnailPath(arg1) {
  return window['go']['app']['App']['GetThumbnailPath'](arg1);
}

export function RemoveTagFromMedia(arg1, arg2) {
  return window['go']['app']['App']['RemoveTagFromMedia'](arg1, arg2);
}

export function SearchMedia(arg1) {
  return window['go']['app']['App']['SearchMedia'](arg1);
}

export function SearchTags(arg1, arg2) {
  return window['go']['app']['App']['SearchTags'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['app']['App']['ToggleFavorite'](arg1);
}

export function UpdateMedia(arg1, arg2) {
  return window['go']['app']['App']['UpdateMedia'](arg1, arg2);
}
