// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApiPort() {
  return window['go']['app']['App']['GetApiPort']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetMediaByID(arg1) {
  return window['go']['app']['App']['GetMediaByID'](arg1);
}

export function SearchMedia(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SearchMedia'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateConfig(arg1) {
  return window['go']['app']['App']['UpdateConfig'](arg1);
}
