// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinalizeUpload(arg1, arg2) {
  return window['go']['app']['App']['FinalizeUpload'](arg1, arg2);
}

export function GetMediaByID(arg1) {
  return window['go']['app']['App']['GetMediaByID'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartUpload(arg1) {
  return window['go']['app']['App']['StartUpload'](arg1);
}

export function UploadChunk(arg1, arg2) {
  return window['go']['app']['App']['UploadChunk'](arg1, arg2);
}
